"""CSDN article search and content crawler."""

import asyncio
from typing import Any, Dict, Iterable, List, Optional
from urllib.parse import urljoin, urlsplit

import httpx
from bs4 import BeautifulSoup
from loguru import logger

from app.services.crawler.base import BaseCrawler


class CSDNCrawler(BaseCrawler):
    """Import CSDN search results, falling back to article-page HTML."""

    SEARCH_URL = "https://so.csdn.net/api/v1/article/getlistArticleListByKeyword"
    SEARCH_HTML_URL = "https://so.csdn.net/so/search"
    _TITLE_KEYS = ("articleTitle", "article_title", "title", "name")
    _URL_KEYS = ("articleUrl", "url", "link", "article_url")
    _CONTENT_KEYS = ("articleContent", "article_content", "content", "markdownContent", "markdown_content", "body", "detail")

    @classmethod
    def _field(cls, article: Dict[str, Any], keys: Iterable[str]) -> str:
        for key in keys:
            value = article.get(key)
            if value is not None and str(value).strip():
                return str(value).strip()
        return ""

    @classmethod
    def _extract_articles(cls, payload: Any) -> List[Dict[str, Any]]:
        """Find article dictionaries in several generations of the API."""

        found: List[Dict[str, Any]] = []
        seen: set[int] = set()

        def visit(value: Any) -> None:
            if isinstance(value, dict):
                title = cls._field(value, cls._TITLE_KEYS)
                url = cls._field(value, cls._URL_KEYS)
                if title or url:
                    marker = id(value)
                    if marker not in seen:
                        seen.add(marker)
                        found.append(value)
                for child in value.values():
                    if isinstance(child, (dict, list)):
                        visit(child)
            elif isinstance(value, list):
                for child in value:
                    visit(child)

        visit(payload)
        return found

    @staticmethod
    def _content_from_html(html: str, fallback_title: str = "") -> tuple[str, str]:
        soup = BeautifulSoup(html or "", "html.parser")
        for node in soup(["script", "style", "noscript", "iframe", "svg"]):
            node.decompose()
        # Remove common navigation/recommendation blocks before selecting the
        # article body. Class names vary, so selectors are intentionally broad.
        for selector in (".recommend-box", ".recommend", ".toolbar", ".comment", ".related", ".blog-footer"):
            for node in soup.select(selector):
                node.decompose()

        title_tag = soup.find("h1") or soup.find("title")
        title = title_tag.get_text(" ", strip=True) if title_tag else fallback_title
        selectors = (
            "#content_views",
            "#article_content",
            "[id^='article_content_']",
            ".markdown_views",
            ".article_content",
            "article",
            "main",
        )
        candidates: List[str] = []
        for selector in selectors:
            for node in soup.select(selector):
                text = node.get_text("\n", strip=True)
                if text:
                    candidates.append(text)
        if not candidates:
            text = soup.get_text("\n", strip=True)
        else:
            text = max(candidates, key=len)
        # Keep line boundaries useful to the chunker while dropping excessive
        # blank lines generated by nested HTML elements.
        lines = [line.strip() for line in text.splitlines() if line.strip()]
        return title.strip(), "\n".join(lines).strip()

    async def crawl(self, keyword: str, max_pages: int = 3) -> List[Dict[str, Any]]:
        keyword = (keyword or "").strip()
        if not keyword:
            return []
        pages = max(1, int(max_pages or 1))
        max_articles = pages * 3
        parsed_target = urlsplit(keyword)
        target_host = parsed_target.hostname.lower() if parsed_target.hostname else ""
        is_csdn_host = target_host == "csdn.net" or target_host.endswith(".csdn.net")
        if parsed_target.scheme in {"http", "https"} and is_csdn_host:
            try:
                async with httpx.AsyncClient(
                    timeout=self.timeout, headers=self.headers, follow_redirects=True
                ) as client:
                    detail = await self._parse_article({"articleUrl": keyword}, client=client)
                return [detail] if detail.get("content") else []
            except Exception as exc:
                logger.error("CSDN 文章 URL 导入失败: {}", exc)
                return []
        params = {"keyword": keyword, "page": 1, "pageSize": max_articles}
        try:
            async with httpx.AsyncClient(
                timeout=self.timeout, headers=self.headers, follow_redirects=True
            ) as client:
                articles: List[Dict[str, Any]] = []
                try:
                    response = await client.get(self.SEARCH_URL, params=params)
                    if getattr(response, "status_code", 0) == 200:
                        try:
                            articles = self._extract_articles(response.json())
                        except Exception as exc:
                            logger.debug("CSDN 搜索接口返回非 JSON: {}", exc)
                except Exception as exc:
                    logger.debug("CSDN 搜索接口请求失败，尝试网页搜索: {}", exc)

                if not articles:
                    articles = await self._search_html(client, keyword, max_articles)

                results: List[Dict[str, Any]] = []
                for article in articles[:max_articles]:
                    try:
                        detail = await self._parse_article(article, client=client)
                        if detail.get("content"):
                            results.append(detail)
                    except Exception as exc:
                        logger.error("解析 CSDN 文章失败: {}", exc)
                    # A scheduling point is enough here; avoid a one-second
                    # delay per article that made imports appear hung.
                    await asyncio.sleep(0)
                return results
        except Exception as exc:
            logger.error("爬取 CSDN 失败: {}", exc)
            return []

    async def _search_html(
        self, client: httpx.AsyncClient, keyword: str, limit: int
    ) -> List[Dict[str, Any]]:
        """Fallback for API outages/shape changes using the public search page."""

        try:
            response = await client.get(self.SEARCH_HTML_URL, params={"q": keyword})
            if getattr(response, "status_code", 0) != 200:
                return []
            soup = BeautifulSoup(response.text or "", "html.parser")
            articles: List[Dict[str, Any]] = []
            seen: set[str] = set()
            for anchor in soup.find_all("a", href=True):
                href = urljoin("https://blog.csdn.net/", anchor["href"])
                if "blog.csdn.net" not in href or href in seen:
                    continue
                title = anchor.get_text(" ", strip=True)
                if not title:
                    continue
                seen.add(href)
                articles.append({"articleTitle": title, "articleUrl": href})
                if len(articles) >= limit:
                    break
            return articles
        except Exception as exc:
            logger.debug("CSDN 网页搜索失败: {}", exc)
            return []

    async def _parse_article(
        self, article: Dict[str, Any], client: Optional[httpx.AsyncClient] = None
    ) -> Dict[str, Any]:
        """Parse an API article, fetching its URL when inline content is absent."""

        title = self._field(article, self._TITLE_KEYS)
        url = self._field(article, self._URL_KEYS)
        if url:
            url = urljoin("https://blog.csdn.net/", url)
        raw_content = self._field(article, self._CONTENT_KEYS)
        if not raw_content and url:
            if client is None:
                async with httpx.AsyncClient(
                    timeout=self.timeout, headers=self.headers, follow_redirects=True
                ) as own_client:
                    return await self._parse_article(article, client=own_client)
            try:
                response = await client.get(url)
                if getattr(response, "status_code", 0) == 200:
                    raw_content = response.text or ""
            except Exception as exc:
                logger.debug("CSDN 文章正文请求失败 {}: {}", url, exc)

        parsed_title, content = self._content_from_html(raw_content, title)
        return {
            "title": (parsed_title or title or "CSDN 文章")[:200],
            "content": content,
            "url": url,
            "source": "csdn",
        }
